name: Deploy Stage To Aws

on:
  push:
    branches: "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd /home/graftonstage-flutemeet-ticket/htdocs/flutemeet-ticket.graftonstage.ie
            git pull
            composer install --no-dev --optimize-autoloader
            npm install
            npm run build
            php artisan optimize
            php artisan migrate --force
            php artisan queue:restart
